export const flowerData = [
    {
      occasion: "Birthday",
      recipient: "Friend",
      budget: "Under $50",
      bouquet: "Bright and Cheerful Mix",
      description: "A vibrant bouquet with daisies, tulips, and sunflowers. Perfect to celebrate the joy and warmth of friendship.",
      meaning: "Daisies symbolize innocence, tulips symbolize perfect love, and sunflowers represent adoration and positivity.",
    },
    {
      occasion: "Birthday",
      recipient: "Family Member",
      budget: "$50-$100",
      bouquet: "Pastel Garden Blooms",
      description: "A delicate mix of pastel roses, lilies, and carnations to show love and care.",
      meaning: "Roses symbolize love, lilies represent purity, and carnations convey admiration.",
    },
    {
      occasion: "Anniversary",
      recipient: "Partner",
      budget: "$50-$100",
      bouquet: "Romantic Red Roses",
      description: "A classic bouquet of red roses with baby's breath.",
      meaning: "Red roses represent deep love and passion, while baby's breath signifies everlasting love.",
    },
    {
      occasion: "Anniversary",
      recipient: "Partner",
      budget: "Over $200",
      bouquet: "Luxury Orchid Arrangement",
      description: "An exotic arrangement of orchids and calla lilies for a truly memorable anniversary.",
      meaning: "Orchids symbolize beauty and strength, while calla lilies signify elegance and devotion.",
    },
    {
      occasion: "Sympathy",
      recipient: "Colleague",
      budget: "Under $50",
      bouquet: "Simple White Lilies",
      description: "A gentle arrangement of white lilies to express sympathy and peace.",
      meaning: "White lilies symbolize purity, peace, and rebirth.",
    },
    {
      occasion: "Sympathy",
      recipient: "Family Member",
      budget: "$50-$100",
      bouquet: "Peaceful Whites",
      description: "A soothing mix of white roses, lilies, and baby's breath.",
      meaning: "White roses signify reverence, and baby's breath symbolizes everlasting remembrance.",
    },
    {
      occasion: "Congratulations",
      recipient: "Friend",
      budget: "$100-$200",
      bouquet: "Vibrant Celebration",
      description: "A colorful mix of gerbera daisies, roses, and lilies to celebrate success.",
      meaning: "Gerbera daisies symbolize cheerfulness, roses represent appreciation, and lilies signify accomplishment.",
    },
    {
      occasion: "Just Because",
      recipient: "Partner",
      budget: "Under $50",
      bouquet: "Sweet Pink Posies",
      description: "A lovely bouquet of pink roses and carnations to show you care.",
      meaning: "Pink roses represent admiration, and pink carnations symbolize gratitude.",
    },
    {
      occasion: "Just Because",
      recipient: "Other",
      budget: "$50-$100",
      bouquet: "Exotic Charm",
      description: "A mix of exotic flowers like birds of paradise and proteas for a unique gift.",
      meaning: "Birds of paradise represent joy and excitement, and proteas symbolize courage and transformation.",
    },
    {
      occasion: "Congratulations",
      recipient: "Colleague",
      budget: "Under $50",
      bouquet: "Classic Yellow Roses",
      description: "A cheerful bouquet of yellow roses to mark a special achievement.",
      meaning: "Yellow roses signify friendship and joy.",
    },
  ];
  