export const flowerData = [
    {
      occasion: "Birthday",
      recipient: "Friend",
      budget: "Under $50",
      bouquet: "Bright and Cheerful Mix",
      description: "A vibrant bouquet with daisies, tulips, and sunflowers. Perfect to celebrate the joy and warmth of friendship.",
      meaning: "Daisies symbolize innocence, tulips symbolize perfect love, and sunflowers represent adoration and positivity.",
    },
    {
      occasion: "Birthday",
      recipient: "Friend",
      budget: "$50-$100",
      bouquet: "Vibrant Friendship Blooms",
      description: "A bold and colorful bouquet with roses, gerbera daisies, and chrysanthemums.",
      meaning: "Roses represent love, gerbera daisies symbolize cheerfulness, and chrysanthemums convey joy and celebration.",
    },
    {
      occasion: "Birthday",
      recipient: "Family Member",
      budget: "$50-$100",
      bouquet: "Pastel Garden Blooms",
      description: "A delicate mix of pastel roses, lilies, and carnations to show love and care.",
      meaning: "Roses symbolize love, lilies represent purity, and carnations convey admiration.",
    },
    {
      occasion: "Birthday",
      recipient: "Family Member",
      budget: "Over $200",
      bouquet: "Grand Family Celebration",
      description: "An extravagant arrangement of orchids, lilies, and hydrangeas to celebrate a special birthday.",
      meaning: "Orchids symbolize beauty, lilies represent purity, and hydrangeas convey heartfelt emotions.",
    },
    {
      occasion: "Anniversary",
      recipient: "Partner",
      budget: "$50-$100",
      bouquet: "Romantic Red Roses",
      description: "A classic bouquet of red roses with baby's breath.",
      meaning: "Red roses represent deep love and passion, while baby's breath signifies everlasting love.",
    },
    {
      occasion: "Anniversary",
      recipient: "Partner",
      budget: "Over $200",
      bouquet: "Luxury Orchid Arrangement",
      description: "An exotic arrangement of orchids and calla lilies for a truly memorable anniversary.",
      meaning: "Orchids symbolize beauty and strength, while calla lilies signify elegance and devotion.",
    },
    {
      occasion: "Anniversary",
      recipient: "Spouse",
      budget: "$100-$200",
      bouquet: "Golden Love",
      description: "A sophisticated mix of golden roses, lilies, and tulips to mark a golden anniversary.",
      meaning: "Golden roses symbolize deep admiration, while lilies represent purity and tulips convey perfect love.",
    },
    {
      occasion: "Sympathy",
      recipient: "Colleague",
      budget: "Under $50",
      bouquet: "Simple White Lilies",
      description: "A gentle arrangement of white lilies to express sympathy and peace.",
      meaning: "White lilies symbolize purity, peace, and rebirth.",
    },
    {
      occasion: "Sympathy",
      recipient: "Colleague",
      budget: "$50-$100",
      bouquet: "Serene Sympathy",
      description: "A calm and elegant mix of white roses, lilies, and orchids for sympathy.",
      meaning: "White roses signify reverence, lilies symbolize peace, and orchids convey strength.",
    },
    {
      occasion: "Sympathy",
      recipient: "Family Member",
      budget: "$50-$100",
      bouquet: "Peaceful Whites",
      description: "A soothing mix of white roses, lilies, and baby's breath.",
      meaning: "White roses signify reverence, and baby's breath symbolizes everlasting remembrance.",
    },
    {
      occasion: "Sympathy",
      recipient: "Family Member",
      budget: "Over $200",
      bouquet: "Majestic White Callas",
      description: "A majestic bouquet of white calla lilies, orchids, and roses for a profound tribute.",
      meaning: "Calla lilies symbolize purity and beauty, while orchids convey love and remembrance.",
    },
    {
      occasion: "Congratulations",
      recipient: "Friend",
      budget: "$100-$200",
      bouquet: "Vibrant Celebration",
      description: "A colorful mix of gerbera daisies, roses, and lilies to celebrate success.",
      meaning: "Gerbera daisies symbolize cheerfulness, roses represent appreciation, and lilies signify accomplishment.",
    },
    {
      occasion: "Congratulations",
      recipient: "Friend",
      budget: "$50-$100",
      bouquet: "Bright Achievement",
      description: "A cheerful bouquet with sunflowers, daisies, and tulips to mark a special moment.",
      meaning: "Sunflowers symbolize admiration, daisies symbolize purity, and tulips convey perfect love.",
    },
    {
      occasion: "Congratulations",
      recipient: "Colleague",
      budget: "Under $50",
      bouquet: "Classic Yellow Roses",
      description: "A cheerful bouquet of yellow roses to mark a special achievement.",
      meaning: "Yellow roses signify friendship and joy.",
    },
    {
      occasion: "Congratulations",
      recipient: "Colleague",
      budget: "$50-$100",
      bouquet: "Celebratory Blooms",
      description: "A vibrant mix of lilies, sunflowers, and daisies for a congratulatory gift.",
      meaning: "Lilies represent accomplishment, sunflowers symbolize admiration, and daisies represent cheerfulness.",
    },
    {
      occasion: "Just Because",
      recipient: "Partner",
      budget: "Under $50",
      bouquet: "Sweet Pink Posies",
      description: "A lovely bouquet of pink roses and carnations to show you care.",
      meaning: "Pink roses represent admiration, and pink carnations symbolize gratitude.",
    },
    {
      occasion: "Just Because",
      recipient: "Other",
      budget: "$50-$100",
      bouquet: "Exotic Charm",
      description: "A mix of exotic flowers like birds of paradise and proteas for a unique gift.",
      meaning: "Birds of paradise represent joy and excitement, and proteas symbolize courage and transformation.",
    },
    {
      occasion: "Just Because",
      recipient: "Friend",
      budget: "$50-$100",
      bouquet: "Casual Chic",
      description: "A charming mix of daisies, roses, and tulips to brighten someone's day.",
      meaning: "Daisies symbolize innocence, roses represent love, and tulips convey perfect love.",
    },
    {
      occasion: "Just Because",
      recipient: "Family Member",
      budget: "Over $200",
      bouquet: "Luxury Family Blooms",
      description: "An extravagant arrangement of orchids, lilies, and roses to express love and care.",
      meaning: "Orchids represent beauty, lilies symbolize purity, and roses convey love and appreciation.",
    },
];
